name : Generate Podcast Feed
on : [push]
jobs :
  build : 
    runs-on : ubuntu-latest
    steps : 
      - name : Checkout repo
        uses: actions/checkout@v4.2.0
      - name : Setup python
        uses: actions/setup-python@v5.2.0
        with : 
          python-version: "3.12"
      - name : Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name : Run Feed Generator
        run : python feed.py
      - name : Push to repo
        run : |
          git config user.name github-actions
          git config user.name github-actions@github.com
          git add .
          git commit -m "Update feed"
          git push
          
